### ISSUE TITLE
Add "variables" and "variables_values" in data object in your index.js

### ISSUE THREAD

**Issue by spaa** [raxraj/fast-two-sms#1]
**UPDATE:**
Please add variables and variables_values in your index,js so that qt route can be used to send dynamic variable messages.

data = {
			sender_id: props.sender_id,
			message: props.message,
			language: props.language,
			route: props.route,
			numbers: nums,
			variables: props.variables,
			variables_values : props.variables_values 
		};
	}

**Comment by raxraj** [comment]
@spaa, sorry for the delay. On it now.

**Comment by raxraj** [comment]
@spaa,
Solved!
